### ISSUE TITLE
'azure-storage' meta-package v0.37.0 is deprecated and cannot be installed anymore

### ISSUE THREAD

**Issue by wyushi** [chatsci/Aeiva#2]
```
$ pip install -r requirements.txt
Collecting Appium_Python_Client==4.3.0
  Downloading appium_python_client-4.3.0.tar.gz (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 KB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting arxiv==2.1.3
  Downloading arxiv-2.1.3-py3-none-any.whl (11 kB)
Collecting azure-storage==0.37.0
  Downloading azure-storage-0.37.0.zip (4.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lp/kqd9d0gj11x46zb30zc38xd40000gn/T/pip-install-wrjbwmip/azure-storage_5cb35ce1be004469a9e910217a7278b2/setup.py", line 55, in <module>
          raise RuntimeError(message)
      RuntimeError:

      Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.

      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all

      Here's a non-exhaustive list of common packages:

      - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
      - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
      - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
      - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by chatsci** [comment]
For your reference, I installed the following:

# create virtual env
conda create --name aeiva
conda activate aeiva

# the python version I'm using
conda install python=3.12 


# install packages
pip install --upgrade pip
pip install numpy
pip install soundfile
pip install pillow   
pip install gradio     
pip install litellm   
pip install torch torchvision torchaudio
pip install transformers
pip install docker
pip install matplotlib
pip install pytest
pip install scipy
pip install pipreqs

pip install mkdocs
pip install mkdocstrings
pip install mkdocs-material
pip install 'mkdocstrings[crystal,python]'

pip install neo4j
pip install --upgrade pymilvus

pip install composio_core composio_openai

pip install --upgrade pyautogui
pip install --upgrade pygame

pip install opencv-python pytesseract

pip install markdownify
pip install arxiv

brew install tesseract

pip install pymupdf
pip install pymupdf4llm
pip install pypdf pdfplumber
brew install ocrmypdf
pip install --upgrade ocrmypdf

pip install mammoth 
pip install docx2pdf   
pip install python-docx

pip install pyobjc
npm i -g appium
brew install node
pip install Appium-Python-Client

pip install dependency-injector

# To install aeiva locally via source code
pip install -e .  

Also, I transferred from pip to poetry later when developing this project, so that may be why some discrepancies happen.

**Comment by chatsci** [comment]
Also, I'm not using azure-storage, so it is safe to remove it.
